/* C code for program chamber, generated by snc from ../chamber.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"

/* Variable declarations */
struct seqg_vars {
# line 3 "../chamber.stt"
	float chamberIn;
# line 4 "../chamber.stt"
	float chamberOut;
# line 5 "../chamber.stt"
	float x;
# line 6 "../chamber.stt"
	float y;
# line 7 "../chamber.stt"
	float go;
# line 8 "../chamber.stt"
	float x_rbv;
# line 9 "../chamber.stt"
	float y_rbv;
# line 10 "../chamber.stt"
	float go_py;
# line 11 "../chamber.stt"
	float go_ny;
# line 12 "../chamber.stt"
	float lim_yb;
# line 13 "../chamber.stt"
	float valve1;
# line 14 "../chamber.stt"
	float valve2;
# line 15 "../chamber.stt"
	float gate;
# line 16 "../chamber.stt"
	float motor_cal;
# line 17 "../chamber.stt"
	float vaccumLow;
# line 18 "../chamber.stt"
	float lim_yt;
# line 19 "../chamber.stt"
	float st;
# line 21 "../chamber.stt"
	float stop;
# line 22 "../chamber.stt"
	float isZeroed;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "chamberIO" ******/

/* Event function for state "init" in state set "chamberIO" */
static seqBool seqg_event_chamberIO_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "chamberIO" */
static void seqg_action_chamberIO_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "TargetInside" in state set "chamberIO" ******/

/* Event function for state "TargetInside" in state set "chamberIO" */
static seqBool seqg_event_chamberIO_0_TargetInside(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 31 "../chamber.stt"
	if (seqg_var->chamberOut == 1)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "TargetInside" in state set "chamberIO" */
static void seqg_action_chamberIO_0_TargetInside(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 32 "../chamber.stt"
			seqg_var->x = 29.5;
# line 33 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 2/*x*/, DEFAULT, DEFAULT_TIMEOUT);
# line 34 "../chamber.stt"
			seqg_var->y = 1;
# line 35 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 3/*y*/, DEFAULT, DEFAULT_TIMEOUT);
# line 36 "../chamber.stt"
			seqg_var->go = 1;
# line 37 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 4/*go*/, DEFAULT, DEFAULT_TIMEOUT);
# line 38 "../chamber.stt"
			seqg_var->st = 1;
# line 39 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 16/*st*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "stage1" in state set "chamberIO" ******/

/* Event function for state "stage1" in state set "chamberIO" */
static seqBool seqg_event_chamberIO_0_stage1(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 43 "../chamber.stt"
	if (fabs(seqg_var->x_rbv - 29.5) < 0.02 && fabs(seqg_var->y_rbv - 1) < 0.02)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 48 "../chamber.stt"
	if (seqg_var->stop == 1)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "stage1" in state set "chamberIO" */
static void seqg_action_chamberIO_0_stage1(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 44 "../chamber.stt"
			seqg_var->go_py = 1;
# line 45 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 7/*go_py*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "stage2" in state set "chamberIO" ******/

/* Event function for state "stage2" in state set "chamberIO" */
static seqBool seqg_event_chamberIO_0_stage2(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 52 "../chamber.stt"
	if (seqg_var->lim_yb == 0)
	{
		*seqg_pnst = 4;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 57 "../chamber.stt"
	if (seqg_var->stop == 1)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "stage2" in state set "chamberIO" */
static void seqg_action_chamberIO_0_stage2(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 53 "../chamber.stt"
			seqg_var->valve2 = 0;
# line 54 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 11/*valve2*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "stage2w" in state set "chamberIO" ******/

/* Event function for state "stage2w" in state set "chamberIO" */
static seqBool seqg_event_chamberIO_0_stage2w(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 61 "../chamber.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 5;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "stage2w" in state set "chamberIO" */
static void seqg_action_chamberIO_0_stage2w(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 62 "../chamber.stt"
			seqg_var->valve1 = 1;
# line 63 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 10/*valve1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 64 "../chamber.stt"
			seqg_var->st = 2;
# line 65 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 16/*st*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "TargetOutside" in state set "chamberIO" ******/

/* Event function for state "TargetOutside" in state set "chamberIO" */
static seqBool seqg_event_chamberIO_0_TargetOutside(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 70 "../chamber.stt"
	if (seqg_var->lim_yb == 0 && seqg_var->chamberIn == 1 && seqg_var->gate == 1)
	{
		*seqg_pnst = 6;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "TargetOutside" in state set "chamberIO" */
static void seqg_action_chamberIO_0_TargetOutside(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 71 "../chamber.stt"
			seqg_var->valve1 = 0;
# line 72 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 10/*valve1*/, DEFAULT, DEFAULT_TIMEOUT);
# line 73 "../chamber.stt"
			seqg_var->st = 3;
# line 74 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 16/*st*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "stage3d" in state set "chamberIO" ******/

/* Event function for state "stage3d" in state set "chamberIO" */
static seqBool seqg_event_chamberIO_0_stage3d(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 79 "../chamber.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 7;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "stage3d" in state set "chamberIO" */
static void seqg_action_chamberIO_0_stage3d(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 80 "../chamber.stt"
			seqg_var->valve2 = 1;
# line 81 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 11/*valve2*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "stage3" in state set "chamberIO" ******/

/* Event function for state "stage3" in state set "chamberIO" */
static seqBool seqg_event_chamberIO_0_stage3(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 86 "../chamber.stt"
	if (seqg_var->vaccumLow < 50)
	{
		*seqg_pnst = 8;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "stage3" in state set "chamberIO" */
static void seqg_action_chamberIO_0_stage3(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 87 "../chamber.stt"
			seqg_var->go_ny = 1;
# line 88 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 8/*go_ny*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "stage4" in state set "chamberIO" ******/

/* Event function for state "stage4" in state set "chamberIO" */
static seqBool seqg_event_chamberIO_0_stage4(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 93 "../chamber.stt"
	if (seqg_var->lim_yt == 0)
	{
		*seqg_pnst = 9;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 98 "../chamber.stt"
	if (seqg_var->stop == 1)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "stage4" in state set "chamberIO" */
static void seqg_action_chamberIO_0_stage4(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 94 "../chamber.stt"
			seqg_var->motor_cal = 1;
# line 95 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 13/*motor_cal*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "stage5" in state set "chamberIO" ******/

/* Event function for state "stage5" in state set "chamberIO" */
static seqBool seqg_event_chamberIO_0_stage5(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 103 "../chamber.stt"
	if (seqg_var->x_rbv == 0 && seqg_var->y_rbv == 0)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 112 "../chamber.stt"
	if (seqg_var->stop == 1)
	{
		*seqg_pnst = 10;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "stage5" in state set "chamberIO" */
static void seqg_action_chamberIO_0_stage5(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 104 "../chamber.stt"
			seqg_var->st = 0;
# line 105 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 16/*st*/, DEFAULT, DEFAULT_TIMEOUT);
# line 106 "../chamber.stt"
			seqg_var->chamberOut = 0;
# line 107 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 1/*chamberOut*/, SYNC, DEFAULT_TIMEOUT);
# line 108 "../chamber.stt"
			seqg_var->chamberIn = 0;
# line 109 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 0/*chamberIn*/, SYNC, DEFAULT_TIMEOUT);
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "force_stop" in state set "chamberIO" ******/

/* Entry function for state "force_stop" in state set "chamberIO" */
static void seqg_entry_chamberIO_0_force_stop(SS_ID seqg_env)
{
# line 118 "../chamber.stt"
	seqg_var->st = 9;
# line 119 "../chamber.stt"
	seq_pvPutTmo(seqg_env, 16/*st*/, DEFAULT, DEFAULT_TIMEOUT);
# line 120 "../chamber.stt"
	seqg_var->isZeroed = 0;
# line 121 "../chamber.stt"
	seq_pvPutTmo(seqg_env, 18/*isZeroed*/, DEFAULT, DEFAULT_TIMEOUT);
}

/* Event function for state "force_stop" in state set "chamberIO" */
static seqBool seqg_event_chamberIO_0_force_stop(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 123 "../chamber.stt"
	if (seqg_var->x_rbv == 0 && seqg_var->y_rbv == 0)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "force_stop" in state set "chamberIO" */
static void seqg_action_chamberIO_0_force_stop(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 124 "../chamber.stt"
			seqg_var->st = 0;
# line 125 "../chamber.stt"
			seq_pvPutTmo(seqg_env, 16/*st*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"CHAM:IN", offsetof(struct seqg_vars, chamberIn), "chamberIn", P_FLOAT, 1, 1, 0, 1, 0, 0},
	{"CHAM:OUT", offsetof(struct seqg_vars, chamberOut), "chamberOut", P_FLOAT, 1, 2, 0, 1, 0, 0},
	{"MOTOR:SET:X", offsetof(struct seqg_vars, x), "x", P_FLOAT, 1, 3, 0, 0, 0, 0},
	{"MOTOR:SET:Y", offsetof(struct seqg_vars, y), "y", P_FLOAT, 1, 4, 0, 0, 0, 0},
	{"MOTOR:MOVE", offsetof(struct seqg_vars, go), "go", P_FLOAT, 1, 5, 0, 0, 0, 0},
	{"MOTOR:X:RBV", offsetof(struct seqg_vars, x_rbv), "x_rbv", P_FLOAT, 1, 6, 0, 1, 0, 0},
	{"MOTOR:Y:RBV", offsetof(struct seqg_vars, y_rbv), "y_rbv", P_FLOAT, 1, 7, 0, 1, 0, 0},
	{"MOTOR:MOVE:PY", offsetof(struct seqg_vars, go_py), "go_py", P_FLOAT, 1, 8, 0, 0, 0, 0},
	{"MOTOR:MOVE:NY", offsetof(struct seqg_vars, go_ny), "go_ny", P_FLOAT, 1, 9, 0, 0, 0, 0},
	{"SW:LIM:BITS.B2", offsetof(struct seqg_vars, lim_yb), "lim_yb", P_FLOAT, 1, 10, 0, 1, 0, 0},
	{"VALVE:TAR:SWITCH", offsetof(struct seqg_vars, valve1), "valve1", P_FLOAT, 1, 11, 0, 0, 0, 0},
	{"VALVE:FORWARD:SWITCH", offsetof(struct seqg_vars, valve2), "valve2", P_FLOAT, 1, 12, 0, 0, 0, 0},
	{"SW:LIM:BITS.B5", offsetof(struct seqg_vars, gate), "gate", P_FLOAT, 1, 13, 0, 1, 0, 0},
	{"MOTOR:CAL", offsetof(struct seqg_vars, motor_cal), "motor_cal", P_FLOAT, 1, 14, 0, 0, 0, 0},
	{"GAU:1:RBV", offsetof(struct seqg_vars, vaccumLow), "vaccumLow", P_FLOAT, 1, 15, 0, 1, 0, 0},
	{"SW:LIM:BITS.B4", offsetof(struct seqg_vars, lim_yt), "lim_yt", P_FLOAT, 1, 16, 0, 1, 0, 0},
	{"PLAT:STATE", offsetof(struct seqg_vars, st), "st", P_FLOAT, 1, 17, 0, 0, 0, 0},
	{"MOTOR:STOP:FORCE", offsetof(struct seqg_vars, stop), "stop", P_FLOAT, 1, 18, 0, 1, 0, 0},
	{"MOTOR:IS:CAL", offsetof(struct seqg_vars, isZeroed), "isZeroed", P_FLOAT, 1, 19, 0, 0, 0, 0},
};

/* Event masks for state set "chamberIO" */
static const seqMask seqg_mask_chamberIO_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_chamberIO_0_TargetInside[] = {
	0x00000004,
};
static const seqMask seqg_mask_chamberIO_0_stage1[] = {
	0x000400c0,
};
static const seqMask seqg_mask_chamberIO_0_stage2[] = {
	0x00040400,
};
static const seqMask seqg_mask_chamberIO_0_stage2w[] = {
	0x00000000,
};
static const seqMask seqg_mask_chamberIO_0_TargetOutside[] = {
	0x00002402,
};
static const seqMask seqg_mask_chamberIO_0_stage3d[] = {
	0x00000000,
};
static const seqMask seqg_mask_chamberIO_0_stage3[] = {
	0x00008000,
};
static const seqMask seqg_mask_chamberIO_0_stage4[] = {
	0x00050000,
};
static const seqMask seqg_mask_chamberIO_0_stage5[] = {
	0x000400c0,
};
static const seqMask seqg_mask_chamberIO_0_force_stop[] = {
	0x000000c0,
};

/* State table for state set "chamberIO" */
static seqState seqg_states_chamberIO[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_chamberIO_0_init,
	/* event function */    seqg_event_chamberIO_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_chamberIO_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "TargetInside",
	/* action function */   seqg_action_chamberIO_0_TargetInside,
	/* event function */    seqg_event_chamberIO_0_TargetInside,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_chamberIO_0_TargetInside,
	/* state options */     (0)
	},
	{
	/* state name */        "stage1",
	/* action function */   seqg_action_chamberIO_0_stage1,
	/* event function */    seqg_event_chamberIO_0_stage1,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_chamberIO_0_stage1,
	/* state options */     (0)
	},
	{
	/* state name */        "stage2",
	/* action function */   seqg_action_chamberIO_0_stage2,
	/* event function */    seqg_event_chamberIO_0_stage2,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_chamberIO_0_stage2,
	/* state options */     (0)
	},
	{
	/* state name */        "stage2w",
	/* action function */   seqg_action_chamberIO_0_stage2w,
	/* event function */    seqg_event_chamberIO_0_stage2w,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_chamberIO_0_stage2w,
	/* state options */     (0)
	},
	{
	/* state name */        "TargetOutside",
	/* action function */   seqg_action_chamberIO_0_TargetOutside,
	/* event function */    seqg_event_chamberIO_0_TargetOutside,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_chamberIO_0_TargetOutside,
	/* state options */     (0)
	},
	{
	/* state name */        "stage3d",
	/* action function */   seqg_action_chamberIO_0_stage3d,
	/* event function */    seqg_event_chamberIO_0_stage3d,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_chamberIO_0_stage3d,
	/* state options */     (0)
	},
	{
	/* state name */        "stage3",
	/* action function */   seqg_action_chamberIO_0_stage3,
	/* event function */    seqg_event_chamberIO_0_stage3,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_chamberIO_0_stage3,
	/* state options */     (0)
	},
	{
	/* state name */        "stage4",
	/* action function */   seqg_action_chamberIO_0_stage4,
	/* event function */    seqg_event_chamberIO_0_stage4,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_chamberIO_0_stage4,
	/* state options */     (0)
	},
	{
	/* state name */        "stage5",
	/* action function */   seqg_action_chamberIO_0_stage5,
	/* event function */    seqg_event_chamberIO_0_stage5,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_chamberIO_0_stage5,
	/* state options */     (0)
	},
	{
	/* state name */        "force_stop",
	/* action function */   seqg_action_chamberIO_0_force_stop,
	/* event function */    seqg_event_chamberIO_0_force_stop,
	/* entry function */    seqg_entry_chamberIO_0_force_stop,
	/* exit function */     0,
	/* event mask array */  seqg_mask_chamberIO_0_force_stop,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "chamberIO",
	/* states */            seqg_states_chamberIO,
	/* number of states */  11
	},
};

/* Program table (global) */
seqProgram chamber = {
	/* magic number */      2002005,
	/* program name */      "chamber",
	/* channels */          seqg_chans,
	/* num. channels */     19,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void chamberRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&chamber);
}
epicsExportRegistrar(chamberRegistrar);
