/* C code for program gauge, generated by snc from ../gauge.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"

/* Variable declarations */
struct seqg_vars {
# line 3 "../gauge.stt"
	float g1;
# line 4 "../gauge.stt"
	float g1Swt;
# line 5 "../gauge.stt"
	float g2;
# line 6 "../gauge.stt"
	float g2Swt;
# line 6 "../gauge.stt"
	float hv_switch;
# line 7 "../gauge.stt"
	float pump_speed;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "checkGauge" ******/

/* Event function for state "init" in state set "checkGauge" */
static seqBool seqg_event_checkGauge_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
	if (TRUE)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "checkGauge" */
static void seqg_action_checkGauge_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 13 "../gauge.stt"
			seqg_var->g1Swt = 1;
# line 14 "../gauge.stt"
			seqg_var->g2Swt = 0;
# line 15 "../gauge.stt"
			seq_pvPutTmo(seqg_env, 1/*g1Swt*/, DEFAULT, DEFAULT_TIMEOUT);
# line 16 "../gauge.stt"
			seq_pvPutTmo(seqg_env, 3/*g2Swt*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "low" in state set "checkGauge" ******/

/* Event function for state "low" in state set "checkGauge" */
static seqBool seqg_event_checkGauge_0_low(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 20 "../gauge.stt"
	if (seqg_var->g1 < 5 && seqg_var->pump_speed > 0.3)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "low" in state set "checkGauge" */
static void seqg_action_checkGauge_0_low(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 21 "../gauge.stt"
			printf("Open high Gauge!");
# line 22 "../gauge.stt"
			seqg_var->g2Swt = 1;
# line 23 "../gauge.stt"
			seq_pvPutTmo(seqg_env, 3/*g2Swt*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "high" in state set "checkGauge" ******/

/* Event function for state "high" in state set "checkGauge" */
static seqBool seqg_event_checkGauge_0_high(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 27 "../gauge.stt"
	if (seqg_var->g1 > 1)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "high" in state set "checkGauge" */
static void seqg_action_checkGauge_0_high(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 28 "../gauge.stt"
			printf("Close High Gauge!");
# line 29 "../gauge.stt"
			seqg_var->g2Swt = 0;
# line 30 "../gauge.stt"
			seq_pvPutTmo(seqg_env, 3/*g2Swt*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"GAU:1:RBV", offsetof(struct seqg_vars, g1), "g1", P_FLOAT, 1, 1, 0, 1, 0, 0},
	{"GAU:1:SWITCH", offsetof(struct seqg_vars, g1Swt), "g1Swt", P_FLOAT, 1, 2, 0, 0, 0, 0},
	{"GAU:2:RBV", offsetof(struct seqg_vars, g2), "g2", P_FLOAT, 1, 3, 0, 1, 0, 0},
	{"GAU:2:SWITCH", offsetof(struct seqg_vars, g2Swt), "g2Swt", P_FLOAT, 1, 4, 0, 0, 0, 0},
	{"HV:SWITCH", offsetof(struct seqg_vars, hv_switch), "hv_switch", P_FLOAT, 1, 5, 0, 0, 0, 0},
	{"PUMP:SPEED", offsetof(struct seqg_vars, pump_speed), "pump_speed", P_FLOAT, 1, 6, 0, 1, 0, 0},
};

/* Event masks for state set "checkGauge" */
static const seqMask seqg_mask_checkGauge_0_init[] = {
	0x00000000,
};
static const seqMask seqg_mask_checkGauge_0_low[] = {
	0x00000042,
};
static const seqMask seqg_mask_checkGauge_0_high[] = {
	0x00000002,
};

/* State table for state set "checkGauge" */
static seqState seqg_states_checkGauge[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_checkGauge_0_init,
	/* event function */    seqg_event_checkGauge_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_checkGauge_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "low",
	/* action function */   seqg_action_checkGauge_0_low,
	/* event function */    seqg_event_checkGauge_0_low,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_checkGauge_0_low,
	/* state options */     (0)
	},
	{
	/* state name */        "high",
	/* action function */   seqg_action_checkGauge_0_high,
	/* event function */    seqg_event_checkGauge_0_high,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_checkGauge_0_high,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "checkGauge",
	/* states */            seqg_states_checkGauge,
	/* number of states */  3
	},
};

/* Program table (global) */
seqProgram gauge = {
	/* magic number */      2002005,
	/* program name */      "gauge",
	/* channels */          seqg_chans,
	/* num. channels */     6,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void gaugeRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&gauge);
}
epicsExportRegistrar(gaugeRegistrar);
