/* C code for program voltage, generated by snc from ../voltage.stt */
#include <string.h>
#include <stddef.h>
#include <stdio.h>
#include <limits.h>

#include "seq_snc.h"
# line 3 "../voltage.stt"

#include <stdlib.h>


/* Variable declarations */
struct seqg_vars {
# line 6 "../voltage.stt"
	float v;
# line 7 "../voltage.stt"
	float i;
# line 8 "../voltage.stt"
	float set;
# line 9 "../voltage.stt"
	float Vtar;
# line 10 "../voltage.stt"
	float sw;
# line 11 "../voltage.stt"
	string msg;
};


/* Function declarations */

#define seqg_var (*(struct seqg_vars *const *)seqg_env)

/* Program init func */
static void seqg_init(PROG_ID seqg_env)
{
}

/****** Code for state "init" in state set "ramp_tar" ******/

/* Event function for state "init" in state set "ramp_tar" */
static seqBool seqg_event_ramp_tar_0_init(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 15 "../voltage.stt"
	if (seqg_var->sw == 1)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 17 "../voltage.stt"
	if (seqg_var->sw == 0)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "init" in state set "ramp_tar" */
static void seqg_action_ramp_tar_0_init(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
		}
		return;
	}
}

/****** Code for state "wait_sw" in state set "ramp_tar" ******/

/* Event function for state "wait_sw" in state set "ramp_tar" */
static seqBool seqg_event_ramp_tar_0_wait_sw(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 21 "../voltage.stt"
	if (seqg_var->sw == 1)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 23 "../voltage.stt"
	if (seqg_var->Vtar)
	{
		*seqg_pnst = 1;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "wait_sw" in state set "ramp_tar" */
static void seqg_action_ramp_tar_0_wait_sw(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	case 1:
		{
			/* C code definitions */
# line 24 "../voltage.stt"
			strcpy(pVar->msg,"Hv Switch is off!");
# line 25 "../voltage.stt"
			seq_pvPutTmo(seqg_env, 5/*msg*/, DEFAULT, DEFAULT_TIMEOUT);
		}
		return;
	}
}

/****** Code for state "wait" in state set "ramp_tar" ******/

/* Event function for state "wait" in state set "ramp_tar" */
static seqBool seqg_event_ramp_tar_0_wait(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 29 "../voltage.stt"
	if (seqg_var->Vtar)
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "wait" in state set "ramp_tar" */
static void seqg_action_ramp_tar_0_wait(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
		}
		return;
	}
}

/****** Code for state "ramp" in state set "ramp_tar" ******/

/* Event function for state "ramp" in state set "ramp_tar" */
static seqBool seqg_event_ramp_tar_0_ramp(SS_ID seqg_env, int *seqg_ptrn, int *seqg_pnst)
{
# line 33 "../voltage.stt"
	if (seq_delay(seqg_env, 1))
	{
		*seqg_pnst = 3;
		*seqg_ptrn = 0;
		return TRUE;
	}
# line 49 "../voltage.stt"
	if (seqg_var->Vtar == seqg_var->set)
	{
		*seqg_pnst = 2;
		*seqg_ptrn = 1;
		return TRUE;
	}
	return FALSE;
}

/* Action function for state "ramp" in state set "ramp_tar" */
static void seqg_action_ramp_tar_0_ramp(SS_ID seqg_env, int seqg_trn, int *seqg_pnst)
{
	switch(seqg_trn)
	{
	case 0:
		{
# line 34 "../voltage.stt"
			seq_pvGetTmo(seqg_env, 3/*Vtar*/, DEFAULT, DEFAULT_TIMEOUT);
# line 35 "../voltage.stt"
			if ((seqg_var->Vtar - seqg_var->set) >= 200)
			{
# line 36 "../voltage.stt"
				seqg_var->set += 200;
# line 37 "../voltage.stt"
				seq_pvPutTmo(seqg_env, 2/*set*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 40 "../voltage.stt"
			if ((seqg_var->Vtar - seqg_var->set) <= -200)
			{
# line 41 "../voltage.stt"
				seqg_var->set += -300;
# line 42 "../voltage.stt"
				seq_pvPutTmo(seqg_env, 2/*set*/, DEFAULT, DEFAULT_TIMEOUT);
			}
# line 44 "../voltage.stt"
			if ((seqg_var->Vtar - seqg_var->set) < 300 && (seqg_var->Vtar - seqg_var->set) > -200)
			{
# line 45 "../voltage.stt"
				seqg_var->set = seqg_var->Vtar;
# line 46 "../voltage.stt"
				seq_pvPutTmo(seqg_env, 2/*set*/, DEFAULT, DEFAULT_TIMEOUT);
			}
		}
		return;
	case 1:
		{
		}
		return;
	}
}

#undef seqg_var

/************************ Tables ************************/

/* Channel table */
static seqChan seqg_chans[] = {
	/* chName, offset, varName, varType, count, eventNum, efId, monitored, queueSize, queueIndex */
	{"HV:{unit}:V:RBV", offsetof(struct seqg_vars, v), "v", P_FLOAT, 1, 1, 0, 1, 0, 0},
	{"HV:{unit}:I:RBV", offsetof(struct seqg_vars, i), "i", P_FLOAT, 1, 2, 0, 1, 0, 0},
	{"HV:{unit}:SET", offsetof(struct seqg_vars, set), "set", P_FLOAT, 1, 3, 0, 0, 0, 0},
	{"HV:{unit}", offsetof(struct seqg_vars, Vtar), "Vtar", P_FLOAT, 1, 4, 0, 1, 0, 0},
	{"HV:SWITCH", offsetof(struct seqg_vars, sw), "sw", P_FLOAT, 1, 5, 0, 1, 0, 0},
	{"SEQ:MSG:HV", offsetof(struct seqg_vars, msg), "msg", P_STRING, 1, 6, 0, 0, 0, 0},
};

/* Event masks for state set "ramp_tar" */
static const seqMask seqg_mask_ramp_tar_0_init[] = {
	0x00000020,
};
static const seqMask seqg_mask_ramp_tar_0_wait_sw[] = {
	0x00000030,
};
static const seqMask seqg_mask_ramp_tar_0_wait[] = {
	0x00000010,
};
static const seqMask seqg_mask_ramp_tar_0_ramp[] = {
	0x00000018,
};

/* State table for state set "ramp_tar" */
static seqState seqg_states_ramp_tar[] = {
	{
	/* state name */        "init",
	/* action function */   seqg_action_ramp_tar_0_init,
	/* event function */    seqg_event_ramp_tar_0_init,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ramp_tar_0_init,
	/* state options */     (0)
	},
	{
	/* state name */        "wait_sw",
	/* action function */   seqg_action_ramp_tar_0_wait_sw,
	/* event function */    seqg_event_ramp_tar_0_wait_sw,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ramp_tar_0_wait_sw,
	/* state options */     (0)
	},
	{
	/* state name */        "wait",
	/* action function */   seqg_action_ramp_tar_0_wait,
	/* event function */    seqg_event_ramp_tar_0_wait,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ramp_tar_0_wait,
	/* state options */     (0)
	},
	{
	/* state name */        "ramp",
	/* action function */   seqg_action_ramp_tar_0_ramp,
	/* event function */    seqg_event_ramp_tar_0_ramp,
	/* entry function */    0,
	/* exit function */     0,
	/* event mask array */  seqg_mask_ramp_tar_0_ramp,
	/* state options */     (0)
	},
};

/* State set table */
static seqSS seqg_statesets[] = {
	{
	/* state set name */    "ramp_tar",
	/* states */            seqg_states_ramp_tar,
	/* number of states */  4
	},
};

/* Program table (global) */
seqProgram voltage = {
	/* magic number */      2002005,
	/* program name */      "voltage",
	/* channels */          seqg_chans,
	/* num. channels */     6,
	/* state sets */        seqg_statesets,
	/* num. state sets */   1,
	/* user var size */     sizeof(struct seqg_vars),
	/* param */             "",
	/* num. event flags */  0,
	/* encoded options */   (0 | OPT_CONN | OPT_NEWEF | OPT_REENT),
	/* init func */         seqg_init,
	/* entry func */        0,
	/* exit func */         0,
	/* num. queues */       0
};

/* Register sequencer commands and program */
#include "epicsExport.h"
static void voltageRegistrar (void) {
    seqRegisterSequencerCommands();
    seqRegisterSequencerProgram (&voltage);
}
epicsExportRegistrar(voltageRegistrar);
